###
GET http://localhost:8080

###
GET http://localhost:8080
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImY5MGZiMWFlMDQ4YTU0OGZiNjgxYWQ2MDkyYjBiODY5ZWE0NjdhYzYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3ByaW5nLWJvb3QtYXV0aGVudGljYXRpb24iLCJhdWQiOiJzcHJpbmctYm9vdC1hdXRoZW50aWNhdGlvbiIsImF1dGhfdGltZSI6MTY1NTg5NzQ4NSwidXNlcl9pZCI6InhPNzNPMlFCY1dQeHNFMWdQcHEwcWdVVjFDNjIiLCJzdWIiOiJ4TzczTzJRQmNXUHhzRTFnUHBxMHFnVVYxQzYyIiwiaWF0IjoxNjU1ODk3NDg1LCJleHAiOjE2NTU5MDEwODUsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYWRtaW5AbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.klSIcerFVjr-JOHQt6o6ytBLtlj7hfngpFNYhFQB0fDdq8lWaalO0w4OOOvor9JzP7XMECcsGMYgc8bFcx43_cIemJYEP0JbEYPHfNdyBXShrBGMs22TA8jcl5g_lHMbhuUpJ7dHwSbDLl70A_imfESm7tBkT9kjsu11LycUn6HLPWFQsxNtn61Q1cWPCte2EbK4MGs58xORLAuJ8hiy0gBKa-9CNpuM9ie099AownU0ku4QqmNDZhfTfb9FsyJjPJyIpknG-a8O6bclEuuKkzQYrJoY-XJp-h3pgHcBdaFzF2on5_HbHELLaY3-RWMz3synV40wRFvs7tEm6rLMAQ

###
GET http://localhost:8080/getUser
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImY5MGZiMWFlMDQ4YTU0OGZiNjgxYWQ2MDkyYjBiODY5ZWE0NjdhYzYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3ByaW5nLWJvb3QtYXV0aGVudGljYXRpb24iLCJhdWQiOiJzcHJpbmctYm9vdC1hdXRoZW50aWNhdGlvbiIsImF1dGhfdGltZSI6MTY1NTg5NzQ4NSwidXNlcl9pZCI6InhPNzNPMlFCY1dQeHNFMWdQcHEwcWdVVjFDNjIiLCJzdWIiOiJ4TzczTzJRQmNXUHhzRTFnUHBxMHFnVVYxQzYyIiwiaWF0IjoxNjU1ODk3NDg1LCJleHAiOjE2NTU5MDEwODUsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYWRtaW5AbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.klSIcerFVjr-JOHQt6o6ytBLtlj7hfngpFNYhFQB0fDdq8lWaalO0w4OOOvor9JzP7XMECcsGMYgc8bFcx43_cIemJYEP0JbEYPHfNdyBXShrBGMs22TA8jcl5g_lHMbhuUpJ7dHwSbDLl70A_imfESm7tBkT9kjsu11LycUn6HLPWFQsxNtn61Q1cWPCte2EbK4MGs58xORLAuJ8hiy0gBKa-9CNpuM9ie099AownU0ku4QqmNDZhfTfb9FsyJjPJyIpknG-a8O6bclEuuKkzQYrJoY-XJp-h3pgHcBdaFzF2on5_HbHELLaY3-RWMz3synV40wRFvs7tEm6rLMAQ
